// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import GlobeController from "./globe_controller"
application.register("globe", GlobeController)

import ForecastController from "./forecast_controller"
application.register("forecast", ForecastController)

import SixhourController from "./sixhour_controller"
application.register("sixhour", SixhourController)
