// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import GlobeController from "./globe_controller"
application.register("globe", GlobeController)

import ForecastController from "./forecast_controller"
application.register("forecast", ForecastController)

import SixhourController from "./sixhour_controller"
application.register("sixhour", SixhourController)

import ScrollerController from "./scroller_controller"
application.register("scroller", ScrollerController)

import GeolocateController from "./geolocate_controller"
application.register("geolocate", GeolocateController)

import JukeboxController from "./jukebox_controller"
application.register("jukebox", JukeboxController)

import MuteController from "./mute_controller"
application.register("mute", MuteController)

import PressController from "./press_controller"
application.register("press", PressController)
