// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName
//
// One controller is deliberately NOT here: globe. It pulls in mapbox-gl, which
// is ~90% of the JavaScript weight and is wanted on one page, so it registers
// itself from app/javascript/globe.js — its own esbuild entry, included only by
// maps/show. stimulus:manifest:update will happily add it back and quietly put
// Mapbox on every page again; javascript_bundles_test.rb fails when it does.

import { application } from "./application"

import ForecastController from "./forecast_controller"
application.register("forecast", ForecastController)

import SixhourController from "./sixhour_controller"
application.register("sixhour", SixhourController)

import ScrollerController from "./scroller_controller"
application.register("scroller", ScrollerController)

import SwipeController from "./swipe_controller"
application.register("swipe", SwipeController)

import GeolocateController from "./geolocate_controller"
application.register("geolocate", GeolocateController)

import JukeboxController from "./jukebox_controller"
application.register("jukebox", JukeboxController)

import MuteController from "./mute_controller"
application.register("mute", MuteController)

import PressController from "./press_controller"
application.register("press", PressController)

import SplashController from "./splash_controller"
application.register("splash", SplashController)

import SequenceController from "./sequence_controller"
application.register("sequence", SequenceController)
